spring:
  application:
    name: Customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/cust_dev
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
